### ISSUE TITLE
Error adding a row

### ISSUE THREAD

**Issue by marksweb** [fsbraun/djangocms-frontend#1]
**Describe the bug**
I've tried to add a row, with 3 columns. No other options changed/selected.

**To Reproduce**
1. Create a row plugin
2. Set the columns to 3
3. Save

**Stacktrace**

```DEBUG middleware AttributeError: 'GridRow' object has no attribute 'numchild'
DEBUG middleware 
127.0.0.1 - - [23/Feb/2022 21:05:37] "POST /admin/cms/placeholder/add-plugin/?placeholder_id=2&plugin_type=GridRowPlugin&cms_path=/admin/cms/placeholder/object/86/edit/1/&plugin_language=en&plugin_position=10&plugin_parent=5 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
    return self.application(environ, start_response)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/views/decorators/clickjacking.py", line 33, in wrapped_view
    resp = view_func(*args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/src/django-cms/cms/admin/placeholderadmin.py", line 372, in add_plugin
    response = plugin_instance.add_view(request)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1586, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/Users/mwalker/Sites/consoles/.venv/src/djangocms-frontend/djangocms_frontend/contrib/grid/cms_plugins.py", line 99, in save_model
    position=obj.numchild,
  File "/Users/mwalker/Sites/consoles/.venv/src/djangocms-frontend/djangocms_frontend/models.py", line 39, in __getattr__
    return super().__getattribute__(item)
AttributeError: 'GridRow' object has no attribute 'numchild'
```

**Comment by fsbraun** [comment]
I cannot reproduce the error. Are there extensions of the Row plugin activated? What version of Django CMS are you using? `numchild` should be an attribute of `CMSPlugin` once it is part of the tree in a placeholder.

**Comment by marksweb** [comment]
@fsbraun oh that's a good point. This is likely a cms v4 compatibility issue. I just don't know what the fix for it is yet.

**Comment by fsbraun** [comment]
As it turns out Django CMS v3 does not require the reference to `.numchild`. It seems it can be removed and `add_child` is taking care of correct positioning in the plugin tree. Just committed a fix which should work on v4, too. (https://github.com/fsbraun/djangocms-frontend/commit/cfb3b58a254ad53cebcb57be714f4fd4b916965d)

Migration from `djangocms_bootstrap4` still references `.numchild`. Before removing it there I need to test if removing does not break the tree during migration. Key element of the migration process is that the plugin ids and the tree are kept in order (since otherwise text-enabled plugins would break).

**Comment by marksweb** [comment]
Fantastic @fsbraun I'll update and look at building my theme & this template again.
