### ISSUE TITLE
django-cms v4 compatibility issue adding plugins

### ISSUE THREAD

**Issue by marksweb** [fsbraun/djangocms-frontend#4]
In django-cms v3 a plugin is based on an `MP_Node` and in turn, plugins here use `obj.add_child()`.

In django-cms v4 plugin's aren't based on `MP_Node`. They're just standard models.

I'm not sure how you want to handle this. Maybe v4 support can move to a new branch which ultimately launches as a new major version of the app. I suppose it may depend on how complex the changes need to be to support v3 and v4 at the same time.

```
Traceback (most recent call last):
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
    return self.application(environ, start_response)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/views/decorators/clickjacking.py", line 33, in wrapped_view
    resp = view_func(*args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/src/django-cms/cms/admin/placeholderadmin.py", line 372, in add_plugin
    response = plugin_instance.add_view(request)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1586, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/Users/mwalker/Sites/consoles/djangocms_frontend/contrib/grid/cms_plugins.py", line 103, in save_model
    obj.add_child(instance=col)
  File "/Users/mwalker/Sites/consoles/djangocms_frontend/models.py", line 39, in __getattr__
    return super().__getattribute__(item)
AttributeError: 'GridRow' object has no attribute 'add_child'
```

**Comment by fsbraun** [comment]
How do you add a v4 plugin to the tree? If have seen it's just a `Model` subclass. W/o treebeard the plugin itself has no idea where it is in the tree. All it sees is its parent and its position. I'd reckon then we do not need a call to `add_child` in the first place. What the call does is setting the `numchild` and `path` field. Is there an equivalent to  a plugin's `path` field in v4?

**Comment by fsbraun** [comment]
Just found out: treebeard does not need the `.add_child` necessarily. It adds `path` some other way, too. Did commit a version without `.add_child`.

**Comment by marksweb** [comment]
> How do you add a v4 plugin to the tree? If have seen it's just a `Model` subclass. W/o treebeard the plugin itself has no idea where it is in the tree. All it sees is its parent and its position. I'd reckon then we do not need a call to `add_child` in the first place. What the call does is setting the `numchild` and `path` field. Is there an equivalent to  a plugin's `path` field in v4?

The front end experience of the structure pane and adding plugins is exactly the same as v3 I think.

I'll have a look when I'm at my machine if there's an equivalent.

**Comment by fsbraun** [comment]
I think I spotted it: `position` has a different meaning in v4 than in v3: In v3 it numbers the child plugins. In v4 it numbers all plugins in one placeholder. Together with the `parent` field this defines the tree. There's probably a reason for this but it means adding a plugin to a placeholder implies increasing the `position` of all plugin instances below. 

In the end it implies there needs to be two cases: one for v3 and one for v4.

**Comment by fsbraun** [comment]
This issue should be solved now through https://github.com/fsbraun/djangocms-frontend/commit/f02ac1eb46dfdc6b5c7a013c9993fdc74c48014a now.

**Comment by fsbraun** [comment]
Finally, closed with https://github.com/fsbraun/djangocms-frontend/commit/7315de1a2ed31e09d2d1db315739007fe21c443b
